### PR TITLE
Add generated code from svd2rust 0.16.1

### PR DESCRIPTION
**Pull request by dflemstr**

### CODE REVIEW

**Comment by thorhs** [comment]
Hi @dflemstr,

Thanks for the PR.  I have not been working on this project for a long time, but am happy to accept patches.  Just to make sure, have you tested this to work, or is it just a 'plain' run of svd2rust?

If tested, I'm willing to just merge and push to crates right away, if not I would like to do some testing first.

**Comment by dflemstr** [comment]
Hey!! Yes, I have a Teensy 3.6 right in front of me, and I was able to make a LED blink :)

**Comment by dflemstr** [comment]
@thorhs do you also mind releasing a crate version at some point containing this change? No rush! Thanks for your help

**Comment by thorhs** [comment]
Published as 0.2.0, thanks for the PR.

**Pull request merged**
